[project]
name = "c9-pulse"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "blinker==1.9.0",
    "certifi==2025.11.12",
    "charset-normalizer==3.4.4",
    "click==8.3.1",
    "colorama==0.4.6",
    "edge-tts>=7.2.7",
    "flask==3.1.2",
    "google-genai>=1.61.0",
    "idna==3.11",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "markupsafe==3.0.3",
    "python-dotenv==1.2.1",
    "requests==2.32.5",
    "urllib3==2.6.2",
    "werkzeug==3.1.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
]
